board/urls.py
from django.urls import path,include
from . import views

app_name = 'board'
urlpatterns = [

    path('list/',views.index, name="list"),
    path('detail/<int:post_id>', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('eidt/<int:post_id>',views.edit, name="edit"),
    path('delete/<int:post_id>',views.delete, name ="delete"),
    path('search/<str:keyword>',views.search, name = "search")
]

main/urls.py
from django.urls import path
from . import views
from posts import views as postview

app_name = 'main'
urlpatterns = [
    path('', views.index, name="index"),
    path('<str:newmenu>/',views.newmenu, name="newmenu"),
    
]

resume/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('accounts.urls')),
    path('board/', include('board.urls')),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.



class Board(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False) 
    subject = models.CharField(max_length=50)
    body = models.TextField()
    image = models.ImageField(upload_to='posts', null=True)
    created_at= models.DateTimeField()
    

    def __str__(self):
        if self.user : return f'{self.user.get_username()}: {self.body}'
        else: return f'{self.body}'

board/views.py
from django.shortcuts import render

# Create your views here.


from django.utils import timezone
from django.shortcuts import redirect, render
from main.models import Menu
from .models import Board
from django.contrib.auth.decorators import login_required


menu= Menu.objects.all()



def index(request):
    inner = Menu.objects.get(name = "board")
    global menu
    posts = Board.objects.all().order_by('-created_at')
    context = {
        'menu' : menu,
        'body' : inner.body,
        'posts': posts,
    }
    return render(request, 'board/index.html', context)  


@login_required
def create(request): 
    inner = Menu.objects.get(name = "board")
    global menu
    context = {
        'menu' : menu,
        'body' : inner.body,
    }

    if request.method =="POST" :
        user = request.user
        subject = request.POST.get('subject')
        body = request.POST.get('body')
        image = request.FILES.get('image')

        post = Board(user=user, subject = subject, body=body, image=image, created_at=timezone.now())
        post.save()
        
        return redirect('board:detail', post_id=post.id)

    elif request.method =="GET" :

        return render(request, 'board/create.html',context)
   
    

def detail(request,post_id):
    post = Board.objects.get(id = post_id)
    inner = Menu.objects.get(name = "board")
    global menu

    context = {
        'menu' : menu,
        'body' : inner.body,
        'post' : post,
    }
    return render(request, "board/detail.html", context)  

@login_required
def edit(request,post_id):
    inner = Menu.objects.get(name = "board")
    global menu

    if request.method == "POST":
        try:
            post = Board.objects.get(id=post_id, user=request.user)
        except Board.DoesNotExist :
            redirect('board:list')
        
        post.subject = request.POST.get('subject')
        post.body =request.POST.get('body')
        image = request.FILES.get('image')
        
        if image :
            post.image = image
        post.save()

        return redirect('board:detail', post_id = post.id) 

    elif request.method == "GET" :
        try:
            post = Board.objects.get(id=post_id, user=request.user)

        except Board.DoesNotExist :
            return redirect('board:list')

        context ={
            'post': post,
            'menu': menu,
            'body': inner.body,}
        return render(request, 'board/edit.html',context)



@login_required
def delete(request,post_id) :
    try :
        post = Board.objects.get(id=post_id, user=request.user)
    except:
        redirect('board:list')
    
    post.delete()
    return redirect('board:list')

    
def search(request,keyword) :
    post =Board.objects.filter(user_text__search='Cheese')
    inner = Menu.objects.get(name = "board")
    global menu
    context = {
        'menu' : menu,
        'body' : inner.body,
        'post' : post,
    }

    return render(request, 'board/index.html', context) 

board/templates/board/create.html
{%extends 'main/base.html'%}

{%load static%}

{%block contents%}
{{ body|safe }}
<div class='container'>
    <h3>New Post</h3>
    <form method="POST" action="{% url 'board:create'%}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class='mb-3 col-md-10'>
            <label class="form-label" for="subject">subject</label>
            <input type="text" class="form-control" name ="subject" id="subject">
        </div>
        <div class='mb-3 col-md-10'>
            <label class="form-label" for="body">body</label>
            <textarea class="form-control" name="body" id="body" cols="30" rows="10"></textarea>
        </div>


        <button type="submit" class="btn btn-secondary">submit</button>
        <a href="{%url 'board:list'%}">
            <button type="button" class="btn btn-secondary">list</button></a>
    </form>

</div>






{%endblock%}

board/templates/board/detail.html
{%extends 'main/base.html'%}

{%load static%}

{%block contents%}
{{ body|safe }}

{% if posts.image %}
<div class='mb-3 col-md-6'>
    <img class="img-fluid" src="{{ posts.image.url }}" alt="Post Image">
</div>
{% endif %}


<table>
    <thead>
        <tr>
            <td><div>
                <label class="form-label" for="subject">subject</label>
                <input type="text" class="form-control" name ="subject" id="subject" value="{{post.subject}}" readonly class="form-control-plaintext">
            </div></td>
        </tr>
        <tr>
            <td><div>
                <label class="form-label" for="author">author</label>
                <input type="text" class="form-control" name ="author" id="author" value="{{post.user.get_username}}" readonly class="form-control-plaintext">
            </div></td>
        </tr>
        <tr>
            <td><div>
                <label class="form-label" for="date">date</label>
                <input type="text" class="form-control" name ="date" id="date" value="{{post.created_at}}" readonly class="form-control-plaintext">
            </div></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><div>
                <label class="form-label" for="body">body</label>
                <textarea class="form-control" name="body" id="body" cols="30" rows="10" readonly>{{ post.body }}</textarea>
            </div></td>
        </tr>
        <tr>
            <td>좋아요 수 : {{posts.liked_users.count}}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td>
                {%if user == post.user%}
                <a href="{%url 'board:edit' post.id%}"><button class="btn btn-secondary">edit</button></a>
                <a href="{%url 'board:delete' post.id%}"><button class="btn btn-secondary">delete</button></a>
                
                {%endif%}
                <a href="{%url 'board:list'%}"><button class="btn btn-secondary">list</button></a></td>
        </tr>
    </tfoot>
</table>




{%endblock%}

board/templates/board/edit.html
{%extends 'main/base.html'%}

{%load static%}

{%block contents%}
{{ body|safe }}
<div class='container'>
    <h3>Edit Post</h3>
    <form method="POST" action="{% url 'board:edit' post.id%}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class='mb-3 col-md-10'>
            <label class="form-label" for="subject">subject</label>
            <input type="text" class="form-control" name ="subject" id="subject" placeholder="{{post.subject}}">
        </div>
        <div class='mb-3 col-md-10'>
            <label class="form-label" for="body">body</label>
            <textarea class="form-control" name="body" id="body" cols="30" rows="10">{{ post.body }}</textarea>
        </div>

        {% if post.image %}
        <label class="form-label" for="img-fluid">active img</label>
        <div class='mb-3 col-md-6'>
            <img class="img-fluid" src="{{ post.image.url }}" alt="Post Image">
        </div>
        {% endif %}
        <div class='mb-3 col-md-10'>
            <label class="form-label" for="image">img</label>
            <input type="file" class="form-control" name="image" id="image">
        </div>

        <button type="submit" class="btn btn-secondary">edit</button>
        <a href="{%url 'board:list'%}">
            <button type="button" class="btn btn-secondary">list</button></a>
    </form>

</div>


{%endblock%}

board/templates/board/index.html
{%extends 'main/base.html'%}

{%load static%}

{%block contents%}

{{ body|safe }}

<table class="table table-hover">
    <thead style ="background-color: #ffb24b; color: white;">

        <td>subject</td>
        <td>author</td>
        <td>like</td>
    </thead>
    <tbody style="color: gray;">
        {%for i in posts%}
        <tr>
        <td><a href= "/board/detail/{{i.id}}" style="color: gray;">{{i.subject}}</a></td>
        <td>{{i.user.get_username}}</td>
        <td>0</td>
        </tr>
        {%endfor%}
    </tbody>
</table>

<table>
    <td>
    <nav style= "min-width: 300px; max-width: 500px;">
        <div class="container-fluid">
          <form class="d-flex" action ="{%url 'board:search' keyword='keyword'%}">
            <input class="form-control me-2" type="search" placeholder="Search" id="keyworld" name ="keyword" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </nav>
      </td>
      <td style="width: max-width;"></td>
    <td style="width: 68px;"><a href="{%url 'board:create'%}">
        <button type="button" class="btn btn-secondary">글쓰기</button></a></td>
</div>




{%endblock%}