accounts/urls.py
from django.urls import path,include
from . import views

app_name = 'accounts'
urlpatterns = [

    path('sign-up/', views.sign_up, name="sign_up"),
    path('login/',views.login, name="login"),
    path('logout/',views.logout, name= "logout"),
    path('',views.dd)
]

main/urls.py
from django.urls import path
from . import views
from posts import views as postview

app_name = 'main'
urlpatterns = [
    path('', views.index, name="index"),
    path('<str:newmenu>/',views.newmenu, name="newmenu"),
    
]

resume/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('accounts.urls')),
    path('board/', include('board.urls')),
]

main/models.py
from django.db import models


class Menu (models.Model): 
    name = models.CharField(max_length=10)
    link = models.CharField(max_length=100)
    body = models.TextField(null=True)

    def __str__(self): 
        return f'{self.name}'

main/views.py
from django.shortcuts import render
from .models import Menu




menu= Menu.objects.all()

# Create your views here.
def index(request):
    inner = Menu.objects.get(name = "about")
    global menu
    context = {
        'menu' : menu,
        'body' : inner.body,
    }
    return render(request, 'main/index.html', context)  



def newmenu(request,newmenu) :
    
    global menu
    inner = Menu.objects.get(name = newmenu)
    try :
        
        context = {'menu' : menu, 'body' : inner.body,}
        return render(request, 'main/index.html', context) 
    except:
        context = {'menu' : menu, 
        'body' :  '<div id="about" class="resume_section"> <h1 class="section-title"><span class="highlight">NO</span> Page</h1> <div class="section-sub-desc">Page does not Exist</div> <p class="section-desc"> please check urls again. page does not exist</p> <ul class="section-icons"></div>'
        }
        return render(request, 'main/index.html', context) 

main/templates/main/base.html
{%load static%}

<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/ba6afde982.js" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main/style.css' %}">
  <title>RESUME</title>
</head>
<body>
  <div id="loginbar">
    <div><h1 class="logo" >♻RESUME</h1></div>
    <div style='display: flex;'>
    {% if user.is_authenticated %}

      <form method="POST" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
    
        {{ user.get_username }}, Welcome !! 
          <button type="submit" class="btn btn-outline-light">LOGOUT</button>
          </form>
          {%if user.is_superuser%}
          <a href="/admin"><button action="button" class="btn btn-light">ADMIN</button></a>
          {%endif%}
        {% else %}
        <form method = "POST" action= "{%url 'accounts:login'%}">
          {%csrf_token%}
          <div style="display: flex;">
              ID: <input class="form-control" id ="username" name="username" type="text" placeholder="아이디">
              PWD: <input class="form-control" id ="password" name="password" type="password" placeholder="비밀번호">
              <button type ="submit" class="btn btn-outline-light">LOGIN</button> 
          </div>
        </form>
        <a href="{%url 'accounts:sign_up'%}"><button type ="submit" class="btn btn-outline-light">sign up</button> </a>
        {%endif%}
        </div>

  
    
  </div>
<div id="resume_container">
  <div class="navbar">
    <img id="profile" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbCsHf5uBlOOhD8eHe_fs6utEl8zYzgx6l4Q&usqp=CAU" alt="Profile">
    <ul class="resume_links">
      {%for i in menu%}
      <li class="resume_link"><a href="/{{i.link}}">{{i.name}}</a></li>
      
      {%endfor%}
    </ul>
  </div>
  <div class="resume_sections">
    <div class="resume_section">

      {%block contents%}
      {%endblock%}
    </div>
  </div>
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/index.html
{%extends 'main/base.html'%}

{%load static%}

{%block contents%}

    {{ body|safe }}
{%endblock%}